FROM registry.access.redhat.com/ubi9/ubi:latest

RUN yum install -y git && yum clean all

RUN curl -L https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64 -o /usr/bin/yq && chmod +x /usr/bin/yq

RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

WORKDIR /workdir

CMD ["/bin/bash"]