# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pipeline:
  appName: "ops-basic-http-demo"
  namespace: "lts-dmz"
  department: "lts"
  network: "dmz"  # LAN or DMZ
  imageRepo: devops-tools
  #
  extra:
    # Set chart wait time before install marked as failed
    installTimeOut: 120
  # 
  tests:
    enabled: false
    type: "cypress"


# Vault:
#   enabled: true
#   VaultUrl: https://vault-k8s.menora.co.il
#   VaultImage: dockerhub/hashicorp/vault-enterprise:1.7.2_ent
#   configMapRef: APPNAME-cm
#   VaultNamespace: lts/ENVIORMENT-dmz-01 # ENVIORMENT-dmz-01 dmz here need to change to lan in case of deployment to lan.
#   VolumeCmName: APPNAME-vault
#   VaultName: APPNAME-ENVIORMENT



#ConfigMap
configmap: 
  enabled: true
  name: APPNAME-cm
  common:
    PORT: "3000"
    # Example env variables 
    ELK_LOGGER_LOGSTASH_TAM_URL: "isc-logstash-tam:9300"
    MONGO_ADDRESS: "isc-mongo-0:27017,isc-mongo-1:27017,isc-mongo-2:27017"
    MINIO_ADDRESS: "minio-bin.bin-data"
    MINIO_ACCESS_KEY: rrrrrrrrrrrrrrr
    MINIO_SECRET_KEY: ttttttttttttttt
    MINIO_PORT: 9000
    MINIO_SSL: false
  int:
    ENVIRONMENT: int
    ENV_CONFIG: int
  qa:
    ENVIRONMENT: qa
    ENV_CONFIG: qa
  prd:
    ENVIRONMENT: prd
    ENV_CONFIG: prod
 
#Secrets
secret:
  enabled: true
  name: APPNAME-secret
  int:
    SC_MONGO_USER: "int123"
  qa:
    SC_MONGO_USER: "qa123"
  prd:
    SC_MONGO_USER: "prd123"

service:
  type: ClusterIP
  port: 3000

resources: 
  # Default
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

# default For java services, uncomment bellow and comment-out/remove the above values.
# resources: 
  # limits:
  #   cpu: 250m
  #   memory: 1024Mi
  # requests:
  #   cpu: 100m
  #   memory: 512Mi

# Readiness probe
readinessProbe:
  enabled: false
  path: /health
  port: 3000
  initialDelaySeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1

# Liveness probe
livenessProbe:
  enabled: false
  path: /health
  port: 3000
  initialDelaySeconds: 20
  timeoutSeconds: 5
  failureThreshold: 30
  periodSeconds: 10
  successThreshold: 1


#######################End#####################
#######################End#####################

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

image:
  repository: IMGREPO
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: IMAGETAG
  tagIsHash: true # default is hash, don't change when deploying using our pipeline.

PackageName: APPNAME-DEPARTMENTENVIORMENT
    
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000



ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: APPNAME-DEPARTMENTENVIORMENT.menora.co.il
      paths: 
        - "/"
  tls: # []
   - secretName: APPNAME-DEPARTMENTENVIORMENT-tls
     hosts:
       - APPNAME-DEPARTMENTENVIORMENT.menora.co.il

hostAliases: # []
# requierd to use vault in dmz environment.
  - ip: x.x.x.x
    hostnames:
      - vault-k8s.menora.co.il

nodeSelector: {}

tolerations: []

affinity: {}

deployenv: {}