apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: render-task
spec:
  params:
    - name: proj
      type: string
    - name: app
      type: string
  steps:
    - name: render-manifest
      image: quay.io/dmarom/pipelineutils:0.0.1
      script: |
        #!/bin/bash

        if [ -z "$proj" ] || [ -z "$app" ]|| [ -z "$GIT_TOKEN" ]; then
            echo "app, proj, GIT_TOKEN should be defined as Env varibles  (proj=$proj app=$app)" 
            exit 1
        fi        
      env:
      - name: GIT_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-token-secret
            key: GIT_TOKEN
      - name: app
        value: $(params.app)
      - name: proj
        value: $(params.proj)