{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}

data:
{{- range $key, $val := .Values.configmap.common }}
  {{ $key }}: "{{ $val }}"
{{- end}}
{{ if eq .Values.deployenv "prd" }}
  {{- range $key, $val := .Values.configmap.prd }}
  {{ $key }}: "{{ $val }}"
  {{- end}}
{{- end }}
{{ if eq .Values.deployenv "qa" }}
  {{- range $key, $val := .Values.configmap.qa }}
  {{ $key }}: "{{ $val }}"
  {{- end}}
{{- end }}
{{ if eq .Values.deployenv "int" }}
  {{- range $key, $val := .Values.configmap.int }}
  {{ $key }}: "{{ $val }}"
  {{- end}}
{{- end }}


{{- end}}
