{{- if .Values.ingress.enabled -}}
{{- $fullName := include "demo.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $isTanzu := eq (include "menorak8s.ingress.isTanzu" .) "true" -}}

{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
  annotations:
  {{- if eq (include "menorak8s.ingress.isTanzu" .) "true" }}
    cert-manager.io/cluster-issuer: cluster-ca-issuer
  {{- end}}
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if eq (include "menorak8s.ingress.isTanzu" .) "true" }}
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      - backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
        path: /
        pathType: ImplementationSpecific
  {{- end }}
  {{- else }}
  {{- range .Values.ingress.hosts }}
  - host: {{ .hosts | quote }}
    http:
      paths:
        {{- range .paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
