# B"H
# Secret to add secret environment variables from values.yaml in use in helpers.tpl
{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
{{ if eq .Values.deployenv "prd" }}
  {{- range $key, $val := .Values.secret.prd }}
  {{ $key }}: "{{ $val | b64enc}}"
  {{- end}}
{{- end }}
{{ if eq .Values.deployenv "qa" }}
  {{- range $key, $val := .Values.secret.qa }}
  {{ $key }}: "{{ $val | b64enc}}"
  {{- end}}
{{- end }}
{{ if eq .Values.deployenv "int" }}
  {{- range $key, $val := .Values.secret.int }}
  {{ $key }}: "{{ $val | b64enc}}"
  {{- end}}
{{- end }}


{{- end}}

