apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  labels:
    app: {{ include "demo.fullname" . }}
    app.kubernetes.io/name: {{ include "demo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    package-name: {{ .Values.PackageName }}
  {{- if .Values.pipeline.extra.labels}}
   {{- range $key, $value := .Values.pipeline.extra.labels }}
    {{ $key }}: {{ $value | quote }}
   {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
