# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pipeline:
  appName: "app4-jmslistener"
  namespace: "qa-app4-namespace"
  department: "bin"
  network: "lan" # LAN or DMZ
  imageRepo: "menora-infbin"
  #
  extra:
    # Set chart wait time before install marked as failed
    dockerfile: "java/java8/springboot/Dockerfile" # Ex: nodejs/current/reactsub/Dockerfile only from repo or in your project 
    dockerignore: "false" # Ex: nodejs/current/reactsub/.dockerignore only from repo or in your project 
    entrypoint: "shared/entrypoint.sh" # Ex: nodejs/current/reactsub/entrypoint only from repo or in your project 
    build_args: ["PRODUCT_ARTIFACT=opti-mivt-dols-gemel-db.jar"] # Ex: nodejs/current/reactsub/args only from repo or in your project 
    #build_target: "builder"
    installTimeOut: 120
    compliance: true # Ex: nodejs/current/reactsub only from repo or in your project. put the command in dockerfile
    labels:
      # seim: default is false. use siem: "qradar" in case you need to send logs to qradar 
      siem: "false"
      index_name: "infra-kubernetes"
      name: dolim-service-monitor
      #any other tags you may need eg
      # foo: "bar"

      APP_VERSION: 0.0.67
  # 

  tests:
    newman:
      enabled: false
      suites:
        test_json: app/tests/postman_collection.json
    cypress:
      enabled: false
      suites:
application:       
  command_args: ["sleep", "infinity"]
  Vault:
    enabled: false
    VaultUrl: https://vault-k8s.menora.co.il
    VaultImage: dockerhub/hashicorp/vault-enterprise:1.7.2_ent
    configMapRef: app4-jmslistener-cm
    VaultNamespace: lts/qa-dmz-01 # qa-dmz-01 dmz here need to change to lan in case of deployment to lan.
    VolumeCmName: app4-jmslistener-vault
    VaultName: app4-jmslistener-qa
    vault_auth_path: auth/k8s-tnz
  #ConfigMap
  configmap:
    enabled: true
    name: app4-jmslistener-cm
    common:
      PORT: "3000"
      
  #Secrets
  secret:
    enabled: true
    name: app4-jmslistener-secret
    int:
      SC_MONGO_USER: "int123"
    
  service:
    type: ClusterIP
    port: 3000
  resources:
    # Default
    limits:
      cpu: 800m
      memory: "100Mi"
    requests:
      cpu: 100m
      memory: "100Mi"
      # default For java services, uncomment bellow and comment-out/remove the above values.
      # resources: 
    # limits:
    #   cpu: 250m
    #   memory: 1024Mi
    # requests:
    #   cpu: 100m
    #   memory: 512Mi
  #Pvc:
  #  enabled: true
  #  name: app4-jmslistener
  #  path: /data
  #  claimName: app4-jmslistener

  # Readiness probe
  readinessProbe:
    enabled: false
    path: /actuator/health
    port: 3000
    initialDelaySeconds: 5
    timeoutSeconds: 1
    failureThreshold: 3
    periodSeconds: 10
    successThreshold: 1
  # Liveness probe
  livenessProbe:
    enabled: false
    path: /actuator/health
    port: 3000
    initialDelaySeconds: 20
    timeoutSeconds: 5
    failureThreshold: 30
    periodSeconds: 10
    successThreshold: 1
  #######################End#####################
  #######################End#####################
  replicaCount: "10"
  autoscaling:
    enabled: false
    minReplicas: "10"
    maxReplicas: "15"
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  image:
    repository: quay.io/thason/gitops-demo
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: e28dc8ebfb4934cf1362f87285ebb7c2f1faf4cf
    tagIsHash: false # default is hash
  PackageName: app4-jmslistener-binqa
  imagePullSecrets: []
  nameOverride: "app4-jmslistener"
  fullnameOverride: ""
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  ingress:
    enabled: true
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: app4-jmslistener-binqa.menora.co.il
        paths:
          - "/"
    tls: # []
      - secretName: app4-jmslistener-binqa-tls
        hosts:
          - app4-jmslistener-binqa.menora.co.il
  hostAliases: # []
    # requierd to use vault in dmz environment.
    - ip: x.x.x.x
      hostnames:
        - vault-k8s.menora.co.il
  nodeSelector: {}
  tolerations: []
  affinity: {}
  deployenv: qa
  AppVersion: 0.0.67
  appName: "app4-jmslistener"
  minReplicas: 10
  maxReplicas: 15
