apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: nginx-ingress-operator.v2.2.0
  namespace: nginx-ingress
  annotations:
    alm-examples: |
      [
        {
          "apiVersion": "charts.nginx.org/v1alpha1",
          "kind": "NginxIngress",
          "metadata": {
            "name": "nginxingress-sample"
          },
          "spec": {
            "controller": {
              "enableCertManager": false,
              "enableCustomResources": true,
              "enableSSLDynamicReload": true
            }
          }
        }
      ]
    capabilities: Basic Install
    categories: 'Networking, Monitoring'
    containerImage: quay.io/nginx/nginx-ingress-operator@sha256:38bb2a104462808eb800445db354535151fbe2632931b9c2a56da3a526923605
    description: The NGINX Ingress Operator deploys and manages one or more NGINX/NGINX Plus Ingress Controllers
spec:
  displayName: Nginx Ingress Operator
  maturity: alpha
  version: 2.2.0
  minKubeVersion: 1.23.0
  provider:
    name: NGINX Inc
  install:
    strategy: deployment
    spec:
      clusterPermissions:
        - serviceAccountName: nginx-ingress-operator-controller-manager
          rules:
            - apiGroups: [""]
              resources: ["namespaces", "configmaps", "secrets"]
              verbs: ["create", "get", "list", "watch", "delete"]
            - apiGroups: ["apps"]
              resources: ["deployments"]
              verbs: ["create", "get", "list", "watch", "delete"]
      deployments:
        - name: nginx-ingress-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            template:
              metadata:
                labels:
                  control-plane: controller-manager
              spec:
                serviceAccountName: nginx-ingress-operator-controller-manager
                containers:
                  - name: manager
                    image: quay.io/nginx/nginx-ingress-operator@sha256:38bb2a104462808eb800445db354535151fbe2632931b9c2a56da3a526923605
                    args:
                      - '--secure-listen-address=0.0.0.0:8443'
                    ports:
                      - containerPort: 8443
                    resources:
                      requests:
                        cpu: "100m"
                        memory: "128Mi"
                      limits:
                        cpu: "500m"
                        memory: "256Mi"