apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: INFRA/argo/
    repoURL: 'https://github.com/danielmarom78/menora24.git'
    targetRevision: devops
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
