apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  name: openshift-gitops
spec:   
  server:
    insecure: true
    autoscale:
      enabled: false
    grpc:
      ingress:
        enabled: false
    ingress:
      enabled: false
    resources:
      limits:
        cpu: 2
        memory: 4G
      requests:
        cpu: 250m
        memory: 1G
    route:
      enabled: true
    service:
      type: ''
  applicationSet:
    env:
      - name: ARGOCD_APPLICATIONSET_CONTROLLER_ENABLE_PROGRESSIVE_SYNCS
        value: 'true'
    resources:
      limits:
        cpu: 2
        memory: 4G
      requests:
        cpu: 250m
        memory: 1G
    webhookServer:
      ingress:
        enabled: false
      route:
        enabled: false
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
      g, cluster-admins, role:admin
      g, gitops-admins, role:admin
    scopes: '[groups]'
  controller:
    processors: {}
    resources:
      limits:
        cpu: 2
        memory: 4G
      requests:
        cpu: 250m
        memory: 1G
    sharding: {}